name: 'Code Review Later'
description: 'Github Action to blocks PRs if closed PRs have not been reviewed in a certain period of time.'
author: 'jakeyheath'
inputs:
  amount:
    required: false
    description: |
      The amount of units to require PRs be code reviewed by.
    default: "5"
  unit:
    required: false
    description: |
      The unit of time to base amount on. Either 'h' for hours or 'd' for days.
    default: "h"
runs:
  using: 'node16'
  main: 'dist/index.js'
